---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: edgeworkertasks.dataspace.ptx.org # <plural>.<group> format
spec:
  group: dataspace.ptx.org
  scope: Namespaced
  names:
    kind: EdgeWorkerTask
    listKind: EdgeWorkerTaskList
    plural: edgeworkertasks
    singular: edgeworkertask
    shortNames:
      - ewt
      - ewts
    categories:
      - all
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          required:
            - spec
          properties:
            spec:
              type: object
              properties:
                data:
                  type: object
                  required:
                    - src
                  properties:
                    src:
                      type: string
                    dst:
                      type: string
                worker:
                  type: object
                  required:
                    - src
                  properties:
                    src:
                      type: string
                    dst:
                      type: string
              required:
                - data
                - worker
            status:
              type: object
              x-kubernetes-preserve-unknown-fields: true
              properties:
                ready:
                  type: boolean
      additionalPrinterColumns:
        - name: Data-Provider
          type: string
          description: Datasource configuration
          jsonPath: .spec.data.src
          priority: 1
        - name: Data-Consumer
          type: string
          description: Worker logic configuration
          jsonPath: .spec.worker.src
          priority: 1
        - name: Status
          type: string
          description: Status
          jsonPath: .status.ready
          priority: 0
        - name: Age
          type: date
          jsonPath: .metadata.creationTimestamp
          priority: 0
---
