---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: edgeworkertasks.dataspace.ptx.org # <plural>.<group> format
spec:
  group: dataspace.ptx.org
  scope: Namespaced
  names:
    plural: edgeworkertasks
    singular: edgeworkertask
    kind: EdgeWorkerTask
    shortNames:
      - ewt
      - ewts
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          required:
            - spec
          properties:
            spec:
              type: object
              properties:
                src:
                  type: object
                dst:
                  type: object
              required:
                - src
                - dst
            status:
              type: object
              x-kubernetes-preserve-unknown-fields: true
              properties:
                ready:
                  type: string
      additionalPrinterColumns:
        - name: DataProvider
          type: string
          description: Datasource configuration
          jsonPath: .spec.src
        - name: DataConsumer
          type: string
          description: Worker logic configuration
          jsonPath: .spec.dst
---
