---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: ${PDC}-${DEF_ZONE}-stripprefix
  namespace: ${PTX_NS}
  labels:
    app: ${PDC}
spec:
  stripPrefix:
    prefixes:
      - /${PDC_SUBPATH}
#---
#apiVersion: traefik.io/v1alpha1
#kind: IngressRoute
#metadata:
#  name: ${PDC}-${DEF_ZONE}
#  namespace: ${PTX_NS}
#  labels:
#    app: ${PDC}
#spec:
#  entryPoints:
#    - web
#  routes:
#    - match: (Host(`${GW_DOMAIN}`) || Host(`${GW_LOCAL_DOMAIN}`) ) && PathPrefix(`/${PDC_SUBPATH}`)
#      kind: Rule
#      middlewares:
#        - name: ${PDC}-${DEF_ZONE}-stripprefix
#          namespace: ${PTX_NS}
#      services:
#        - name: ${PDC}-${DEF_ZONE}
#          port: ${PDC_DEF_PORT}
#  tls:
#    secretName: gw-tls
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ${PDC}-${DEF_ZONE}
  namespace: ${PTX_NS}
  labels:
    app: ${PDC}
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.middlewares: ${PTX_NS}-${PDC}-${DEF_ZONE}-stripprefix@kubernetescrd
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.tls.certresolver: letsencrypt
    traefik.ingress.kubernetes.io/router.tls.domains.0.main: ${GW_DOMAIN}
spec:
  ingressClassName: traefik
  rules:
    - host: ${GW_DOMAIN}
      http:
        paths:
          - path: /${PDC_SUBPATH}
            pathType: Prefix
            backend:
              service:
                name: ${PDC}-${DEF_ZONE}
                port:
                  number: ${PDC_DEF_PORT}
    - host: ${GW_LOCAL_DOMAIN}
      http:
        paths:
          - path: /${PDC_SUBPATH}
            pathType: Prefix
            backend:
              service:
                name: ${PDC}-${DEF_ZONE}
                port:
                  number: ${PDC_DEF_PORT}
  tls:
    #- secretName: gw-tls
    - hosts:
        - ${GW_DOMAIN}
---